# Generated by Django 5.1.3 on 2024-12-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_favoritehotel_delete_customerlocationhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='HotelandRestro',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
