# Generated by Django 5.1.3 on 2024-12-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_hotel_hotelandrestro_delete_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelandRestro',
            new_name='Hotel_Restro',
        ),
    ]
