# Generated by Django 5.1.3 on 2024-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_hotel_restro_hotelrestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritehotel',
            name='phone',
            field=models.CharField(default='No phone.no. available', max_length=12),
        ),
    ]
