# Generated by Django 5.1.3 on 2024-12-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_favoritehotel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrestro',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotelrestro',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='hotelrestro',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
