# Generated by Django 5.1.3 on 2024-12-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_remove_review_comment_review_review_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
