# Generated by Django 5.1.3 on 2024-12-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_remove_review_review_text_review_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
